In [1]:
from tqdm import tqdm
import torch
from llm_utils.llm_loader import load_llm
from utils.prompt import Prompter
from llm_utils.llm_generation import LLMGeneration
from utils.store_data import StoreData
from utils.arguments import Arguments
from dataset_loaders import load_data, ImageDataset
from dataset_loaders.utils import data_sampler
import os
from datasets import Dataset
from torch.utils.data import DataLoader
from dataset_loaders.ScienceQA import ScienceQA
from PIL import Image
import numpy as np

In [2]:
normalizer = lambda x: x / (np.linalg.norm(x, ord=2, axis=-1, keepdims=True) + 1e-10)

In [3]:
X=np.array([
    [1,2,3],
    [1,2,3]
])
X

array([[1, 2, 3],
       [1, 2, 3]])

In [4]:
np.sum(X,-1)

array([6, 6])

In [8]:
np.linalg.norm(X, ord=2, axis=1)

array([3.74165739, 3.74165739])

In [4]:
mu = X.mean(axis=0)

array([1.5, 2. , 2.5])

In [6]:
X=X-mu
X

array([[-0.5,  0. ,  0.5],
       [ 0.5,  0. , -0.5]])

In [1]:
from tqdm import tqdm
import time

# Outer loop progress bar
outer_iterations = 5
inner_iterations = 10

for i in tqdm(range(outer_iterations), desc='Outer Loop'):
    # Inner loop progress bar
    for j in tqdm(range(inner_iterations), desc='Inner Loop', leave=False):
        time.sleep(0.1)  # Simulate work

print("Task completed!")


Outer Loop: 100%|██████████| 5/5 [00:05<00:00,  1.05s/it]

Task completed!
